### ISSUE TITLE
Https conflict?

### ISSUE THREAD

**Issue by FuriousDuck** [AutomatedTester/browsermob-proxy-py#19]
I try to test GA events in my app, using browsermob. I run my webdriver with options (code sample from my setUp() method)
`
self.client = Client("localhost:2000")
self.proxy = Proxy({
    'proxyType': ProxyType.MANUAL,
    'httpProxy': self.client.proxy,
    'ftpProxy': self.client.proxy,
    'sslProxy': self.client.proxy,
    'noProxy': '' # set this value as desired
})
self.driver = webdriver.Firefox(proxy=self.proxy)
`
Every event on `http` works fine and browsermob writes it to HAR right, but when I try to do the same on `https`, some events seem not to happen at all. If I start browser without a proxy, they work fine.

**Comment by AutomatedTester** [comment]
Closing as no answer was received

**Comment by jesus-sayar** [comment]
Some new solution for this problem?
