### ISSUE TITLE
response interceptor doesn't chagne response content

### ISSUE THREAD

**Issue by stavanmehta** [AutomatedTester/browsermob-proxy-py#45]
I tried response interceptor as per your test method. But it only returns 200 status code. and doesn't change response content. 
Also, I saw proxy server change at https://github.com/lightbody/browsermob-proxy project. 
are you planning to update your project with littleproxy instead or Jetty?

def test_response_interceptor_with_parsing_js(self):
        """
        /proxy/:port/interceptor/response
        """
        js = 'alert("foo")'
        status_code = self.client.response_interceptor(js)
        assert(status_code == 200)

**Comment by AutomatedTester** [comment]
This project is just a client library to speak to the https://github.com/lightbody/browsermob-proxy  java proxy. If you are getting a status code that doesnt match what you want then I suggest raising a bug there. 

Same for the question about littleproxy/jetty
