### ISSUE TITLE
server.start() gives error

### ISSUE THREAD

**Issue by Kidder77** [AutomatedTester/browsermob-proxy-py#52]
Hi everyone,

I'm trying to run a PhantomJS webdriver with BrowserMob-proxy using Selenium in Python. It's the first time for me and the basic "getting started" code provided [here](https://github.com/AutomatedTester/browsermob-proxy-py/)  is already returning error.

```
from browsermobproxy import Server
server = Server('browsermob-proxy-2.0.0\\bin\\browsermob-proxy') #I also tried browsermob-proxy-2.1.0-beta-6 but the error stays the same
server.start()
proxy = server.create_proxy()
```

I get this error:
```
>>> server.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\Python27\lib\site-packages\browsermobproxy\server.py", line 104, in start
    raise Exception("Can't connect to Browsermob-Proxy")
Exception: Can't connect to Browsermob-Proxy
```

I downloaded the Python library simply with pip install browsermob-proxy. (version 0.7.0)

I downloaded both versions of BrowserMob proxy from https://github.com/lightbody/browsermob-proxy/releases

I'm using Python 2.7.11 on Windows 10.

Any idea what I'm doing wrong? It seems like I'm stuck at the very start and I'm clueless as I don't have virtually any experience with this.

Any help would be much appreciated!

**Comment by mbcc2006** [comment]
you hava a wrong path , you can use absolute path like this r"D:\tobao\bbp\bin\browsermob-proxy" ,do not add '.bat'

**Comment by AutomatedTester** [comment]
as @mbcc2006 said, you need to make sure it goes to the browsermob executable.
