### ISSUE TITLE
server.start() permission deny

### ISSUE THREAD

**Issue by zhmin** [AutomatedTester/browsermob-proxy-py#53]
I'm on mac, sever.start() raise error: Permission denied: '/server.log'.
It's because 
log_path_name = os.path.join(log_path, os.path.sep, log_file) in start method.
log_path_name return '/server.log'.

I change code,  log_path_name = os.path.join(log_path,  log_file).
then it's ok

**Comment by AutomatedTester** [comment]
The correct way to do it is with `log_path_name = os.path.join(log_path, log_file)`
