### ISSUE TITLE
Server is not starting when we are behind proxy

### ISSUE THREAD

**Issue by vuyyala** [AutomatedTester/browsermob-proxy-py#56]
Hi All,
       I am using proxy to connect to net so when I am trying to start browsermob proxy server it is unable to get started.How to run the server when I am behind the proxy?

server=Server('path to  browsermob-proxy')
server.start()
proxy=server.create_proxy()

**Comment by vuyyala** [comment]
Anyone there to help please?

**Comment by AutomatedTester** [comment]
Unfortunately I have never set up behind a proxy. Perhaps try the BrowserMob Proxy Google Group
