### ISSUE TITLE
Force BrowserMobProxy and Selenium Chrome Driver to use QUIC

### ISSUE THREAD

**Issue by vuyyala** [AutomatedTester/browsermob-proxy-py#60]
Hi all, 
        I am working on downloading HAR from Chrome for YouTube through Selenium Python Script.
Code Snippet: 

                chrome_options = webdriver.ChromeOptions()
        	chrome_options.add_argument("--proxy-server={0}".format(url))
		chrome_options.add_argument("--enable-quic")

        	self.driver = webdriver.Chrome(chromedriver,chrome_options = chrome_options)

               self.proxy.new_har(args['url'], options={'captureHeaders': True})   // BrowserMobProxy
	       self.driver.get(args['url'])
               result = json.dumps(self.proxy.har, ensure_ascii=False)

I want QUIC to be used whenever I download HAR but when I look at the packets through Wireshark Selenium driver is using TCP only . Is there a way to force BrowserMobProxy and  Chrome Driver to use QUIC?

**Comment by AutomatedTester** [comment]
I dont know what QUIC is. 

Selenium uses HTTP to send commands between the client and the remote end so natually uses TCP.

**Comment by vuyyala** [comment]
But Selenium Webdriver has  Chrome Options to which an argument like 'Enable QUIC' can be added.So if anyone else have an idea about this please comment.

**Comment by AutomatedTester** [comment]
I suggest raising this with the ChromeDriver folk  Or you can send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
