### ISSUE TITLE
Getting the error "browsermobproxy.exceptions.ProxyServerError"

### ISSUE THREAD

**Issue by samukherjee** [AutomatedTester/browsermob-proxy-py#91]
Traceback (most recent call last):
  File "getTrending.py", line 7, in <module>
    api = TikTokapi()
  File "C:\Users\Sagar\Downloads\TikTok-Api-master\tiktok.py", line 18, in __ini
t__
    server.start()
  File "C:\Users\Sagar\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\browsermobproxy\server.py", line 122, in start
    raise ProxyServerError(message)
browsermobproxy.exceptions.ProxyServerError: The Browsermob-Proxy server process
 failed to start. Check <_io.TextIOWrapper name='C:\\Users\\Sagar\\Downloads\\Ti
kTok-Api-master\\server.log' mode='w' encoding='cp1252'>for a helpful error mess
age.

using python 3 on windows7...

**Comment by samukherjee** [comment]
Using the Code Below..

def __init__(self):
        print("New class reference, finding valid signature. This might take a minute.")
        from browsermobproxy import Server
        import psutil
        import json
        import time

        for proc in psutil.process_iter():
            # check whether the process name matches
            if proc.name() == "browsermob-proxy":
                proc.kill()

        dict = {'port': 8090}
        server = Server(
            path="C:/Users/Sagar/Downloads/TikTok-Api-master/browsermob-proxy/bin/browsermob-proxy", options={'port': 9090})
        server.start()
        time.sleep(1)
        proxy = server.create_proxy()
        time.sleep(1)
        from selenium import webdriver
        profile = webdriver.FirefoxProfile()
        selenium_proxy = proxy.selenium_proxy()
        profile.set_proxy(selenium_proxy)
        driver = webdriver.Firefox(firefox_profile=profile)

        proxy.new_har("list")
        driver.get("https://www.tiktok.com/en/trending")
        data = proxy.har
        for element in data['log']['entries']:
            if "https: //www.tiktok.com/share/item/list?" in element['request']['url'] or "https://www.tiktok.com/share/item/list?" in element['request']['url']:
                print("Found signature, continuing.")
                self.signature = element['request']['queryString'][6]['value']

        server.stop()
        driver.quit()

**Comment by samukherjee** [comment]
Getting the solution by installing java and set the PATH environment variable.

**Comment by Rain1560** [comment]
But why my BMP still rasises ProxyServerError after installing java and set the PATH environment variable?
